### ISSUE TITLE
lr.artemislena.eu onion

### ISSUE THREAD

**Issue by artemislena** [libreddit/libreddit-instances#19]
L: Hey, uhm, @Daniel-Valentine, when you added our clearnet instance lr.artemislena.eu from #18, you forgot our onion instance `http://lr.lpoaj7z2zkajuhgnlltpeqh3zyq7wk2iyeggqaduhgxhyajtdt2j7wad.onion,DE,false,""`.

**Comment by Daniel-Valentine** [comment]
Apologies. The instances list has been updated with your onion instance.
